parameters:
    nextdev_adr.classfinder.cache: '%kernel.cache_dir%/loadable_classes.php'

services:
    _defaults:
        autowire: true

    nextdev\AdrBundle\Command\ResponderDebugCommand:
        tags: ['console.command']

    nextdev\AdrBundle\EventSubscriber\ControllerSubscriber:
        tags: ['kernel.event_subscriber']
        
    nextdev\AdrBundle\EventSubscriber\ViewSubscriber:
        tags: ['kernel.event_subscriber']

    nextdev\AdrBundle\Responder\Responder:

    nextdev\AdrBundle\Responder\ScalarHandler:
        tags:
            - { name: nextdev_adr.responder, priority: -1024 }

    nextdev\AdrBundle\Responder\ObjectHandler:
        tags:
            - { name: nextdev_adr.responder, priority: -1024 }

    nextdev\AdrBundle\Util\ClassFinder:
        factory: '@nextdev\AdrBundle\Util\ClassFinderFactory'

    nextdev\AdrBundle\Util\ClassFinderFactory:
