parameters:
    pitch_adr.classfinder.cache: '%kernel.cache_dir%/loadable_classes.php'

services:
    _defaults:
        autowire: true

    Pitch\AdrBundle\Command\ResponderDebugCommand:
        tags: ['console.command']

    Pitch\AdrBundle\EventSubscriber\ControllerSubscriber:
        tags: ['kernel.event_subscriber']
        
    Pitch\AdrBundle\EventSubscriber\ViewSubscriber:
        tags: ['kernel.event_subscriber']

    Pitch\AdrBundle\Responder\Responder:

    Pitch\AdrBundle\Responder\Handler\ScalarHandler:
        tags:
            - { name: pitch_adr.responder, priority: -1024 }

    Pitch\AdrBundle\Responder\Handler\ObjectHandler:
        tags:
            - { name: pitch_adr.responder, priority: -1024 }

    Pitch\AdrBundle\Util\ClassFinder:
        factory: '@Pitch\AdrBundle\Util\ClassFinderFactory'

    Pitch\AdrBundle\Util\ClassFinderFactory:
